### PR TITLE
update all npm deps to latest minor / patch versions

### PR DESCRIPTION
**Pull request by samgqroberts**
this is the easiest thing to do right now to start addressing the security vulnerabilities that github keeps squawking about https://github.com/SylverStudios/WatchWithMe/network/alerts

after we merge this (if the tests pass, obviously) we can spot check which of those alerts actually required major bumps, and then be a little more careful about updating

### CODE REVIEW

**Comment by samgqroberts** [comment]
oh hey look minor bumps made the tests fail
a) thanks travis!
b) classic javascript dependencies

**Comment by samgqroberts** [comment]
16.2 -> 16.8 for react and react-dom actually constitutes like a year and a half of development on both those projects. maybe we don't go gung-ho on those quite yet

**Comment by samgqroberts** [comment]
updated without react/react-dom updates, with another driveby: move eslint to devDependencies. see commit message for more details

**Comment by shamshirz** [comment]
These test failures look like server side issues? Dependabot put up a react PR that worked, I'm going to start merging those 1 at a time and come back to this after a few of those

**Pull request closed without merging**
